PL/Models/ErrorViewModel.cs
namespace PL.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PL/Controllers/AutomovilController.cs
using Microsoft.AspNetCore.Mvc;

namespace PL.Controllers
{
    public class AutomovilController : Controller
    {
        public ActionResult GetAll()
        {
            ML.Automovil automovil = new ML.Automovil();
            ML.Result result = BL.Automovil.GetAll();
            automovil.Automoviles = result.Objects;
            return View(automovil);
        }
        [HttpGet]
        public ActionResult Delete(int IdAutomovil)
        {
            ML.Result result = BL.Automovil.Delete(IdAutomovil);
            if (result.Correct)
            {
                ViewBag.Message = "Registro eliminado";
                return PartialView("Modal");

            }
            else
            {
                ViewBag.Message = "Error";
                return PartialView("Modal");
            }
        }
        public ActionResult Form(int? IdAutomovil)
        {
            ML.Automovil automovil = new ML.Automovil();
            if (IdAutomovil == null)
            {
                return View(automovil);
            }
            else
            {
                ML.Result result = BL.Automovil.GetById(IdAutomovil.Value);
                if (result.Correct)
                {
                    automovil = (ML.Automovil)result.Object;
                    return View(automovil);
                }
                else
                {
                    return View();
                }
            }
        }
        [HttpPost]
        public ActionResult Form(ML.Automovil automovil)
        {
            if (automovil.IdAutomovil == 0)
            {
                ML.Result result = new ML.Result();
                result = BL.Automovil.Add(automovil);
                if (result.Correct)
                {
                    ViewBag.Message = "Registro agregado";
                    return PartialView("Modal");
                }
                else
                {
                    ViewBag.Message = "Error al agregar";
                    return PartialView("Modal");
                }
            }
            else
            {
                ML.Result result = new ML.Result();
                result = BL.Automovil.Update(automovil);
                if (result.Correct)
                {
                    ViewBag.Message = "Registro actualizado";
                    return PartialView("Modal");
                }
                else
                {
                    ViewBag.Message = "Error al actualizar";
                    return PartialView("Modal");
                }
            }

        }

    }
}

PL/Controllers/EstacionamientoController.cs
using Microsoft.AspNetCore.Mvc;

namespace PL.Controllers
{
    public class EstacionamientoController : Controller
    {
        public ActionResult Form(int IdUsuario)
        {
            ML.Result resultAutomovil = BL.Automovil.GetAll();
            ML.Usuario usuario = new ML.Usuario();
            usuario.Automovil = new ML.Automovil();
            if (resultAutomovil.Correct)
            {
                usuario.Automovil.Automoviles = resultAutomovil.Objects;
            }
            if (IdUsuario == 0)
            {
                return View(usuario);
            }
            else
            {
                return View(null);
            }
        }
    }
}

PL/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PL.Models;
using System.Diagnostics;

namespace PL.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PL/Controllers/UsuarioController.cs
using Microsoft.AspNetCore.Mvc;

namespace PL.Controllers
{
    public class UsuarioController : Controller
    {
        public ActionResult GetAll()
        {
            ML.Usuario usuario = new ML.Usuario();
            ML.Result result = BL.Usuario.GetAll();
            usuario.Usuarios = result.Objects;
            return View(usuario);
        }
        public ActionResult Delete(int IdUsuario)
        {
            ML.Result result = BL.Usuario.Delete(IdUsuario);
            if (result.Correct = true)
            {
                ViewBag.Message = "Registro eliminado";
                return PartialView("ModalU");
            }
            else
            {
                ViewBag.Message = "Error";
                return PartialView("ModalU");
            }
        }
        public ActionResult Form(int IdUsuario)
        {
            
            ML.Result resultAutomovil = BL.Automovil.GetAll();
            ML.Usuario usuario = new ML.Usuario();
            usuario.Automovil= new ML.Automovil();

            if (resultAutomovil.Correct)
            {
                usuario.Automovil.Automoviles = resultAutomovil.Objects;
            }
            if (IdUsuario == 0)
            {
                return View(usuario);
            }
            else
            {
                ML.Result result = BL.Usuario.GetById(IdUsuario);
                if (result.Correct)
                {
                    usuario = (ML.Usuario)result.Object;
                    usuario.Automovil.Automoviles = resultAutomovil.Objects;
                    return View(usuario);
                }
                else
                {
                    return View(null);
                }
            }
        }
        [HttpPost]
        public ActionResult Form(ML.Usuario usuario)
        {
            if (usuario.IdUsuario == 0)
            {
                ML.Result result = new ML.Result();
                result = BL.Usuario.Add(usuario);
                if (result.Correct = true)
                {
                    ViewBag.Message = "Registro agregado";
                    return PartialView("ModalU");
                }
                else
                {
                    ViewBag.Message = "Error";
                    return PartialView("ModalU");
                }
            }
            else
            {
                ML.Result result = new ML.Result();
                result = BL.Usuario.Update(usuario);
                if (result.Correct)
                {
                    ViewBag.Message = "Registro actualizado";
                    return PartialView("ModalU");
                }
                else
                {
                    ViewBag.Message = "Error";
                    return PartialView("ModalU");
                }
            }
        }
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(string Username, string Contrasena)
        {
            ML.Result result = BL.Usuario.GetByUsername(Username);
            if (result.Correct)
            {
                ML.Usuario usuario = (ML.Usuario)result.Object;
                if (Contrasena == usuario.Contrasena)
                {
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ViewBag.Message = "La contraseña no coincide";
                    return PartialView("LoginModal");
                }
            }
            else
            {
                ViewBag.Messge = "El usuario no existe";
                return PartialView("LoginModal");
            }
        }

    }
}

PL/Views/Automovil/Form.cshtml
@model ML.Automovil
@{
    ViewData["Title"] = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <center>
                <h1 style="color:#6EB5FF">Registro de Autos</h1>
            </center>
        </div>
        <div class="row">
        </div>
    </div>
    @using (Html.BeginForm("Form", "Automovil", FormMethod.Post, new { enctype = "multipart/form-data", @id = "Automovil" }))
    {
        <div class="row">
            <div class="col-md-3" style="display: none;">
                @Html.TextBoxFor(model => model.IdAutomovil, new { @class = "hidden form-control", autocomplete = "off", @id = "IdAutomovil" })
            </div>
        </div>
        <div class="row">
            <div class="col-md-3">
                @Html.Label("Placa")
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1"></span>
                    <div class="input-group mb-3">
                        <span class="input-group-text" id="basic-addon1"><i class="fa-solid fa-capsules"></i></span>
                        @Html.TextBoxFor(model => model.Placa, new { @class = "form-control",  @id = "placa",placeholder="XXX-XXX-XXX"})
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-2">
                <input type="submit" value="Guardar" class="btn btn-success" />
            </div>
            <div class="col-md-2">
                @Html.ActionLink("Regresar", "GetAll", "Automovil", htmlAttributes: new { @class = "btn btn-success" })
            </div>
        </div>

    }
</div>

PL/Views/Automovil/GetAll.cshtml
@{
    ViewData["Title"] = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>


<div class="row">
    <div style="float:right;">
        @Html.ActionLink("Agregar Automovil", "Form", "Automovil", htmlAttributes: new { @class = "btn btn-primary" })
    </div>
</div>
<hr />

<div class="row">
    @if (Model.Automoviles != null)
    {
        <table class="table table-light table-bordered table-responsive table-hover" id="tblAutomovil">
            <thead>
                <tr>

                    <td class="table-info text-center" style=" font-weight:bold;">Editar</td>
                    <td class="d-none">IdAutomovil</td>
                    <td class="table-info text-center" style=" font-weight:bold;">Placa</td>
                    <td class="table-info text-center" style=" font-weight:bold;">Eliminar</td>

                </tr>
            </thead>
            <tbody>

                @foreach (ML.Automovil automovil in Model.Automoviles)
                {
                    <tr>
                        <td class="text-center"><a class="btn btn-warning" href="@Url.Action("Form", "Automovil", new { IdAutomovil = automovil.IdAutomovil })"><i class="fa-regular fa-pen-to-square" style="color: red;"></i> </a></td>
                        <td class="d-none">@automovil.IdAutomovil</td>
                        <td class="text-center">@automovil.Placa</td>
                        <td style="text-align: center; vertical-align: middle;"><a class="btn btn-danger" href="@Url.Action("Delete", "Automovil", new { IdAutomovil = automovil.IdAutomovil })" onclick="return confirm('Estas seguro que deseas eliminar este registro?');"><i class="fa-regular fa-trash-can"></i></a></td>
                    </tr>
                }
            </tbody>
        </table>

    }
    else
    {
        <div class="alert alert-danger" role="alert">Ocurrio un error al realizar la consulta </div>
    }
</div>

PL/Views/Estacionamiento/Form.cshtml
@model ML.Usuario
@{
    ViewData["Title"] = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <center>
            <h1 style="color:#332042">Registro de Estacionamiento</h1>
        </center>
    </div>
    <div class="row">
    </div>
</div>

    
    <div class="container" style="text-align: center;">
        
        <div class="row">
            
        @using (Html.BeginForm("Form", "Usuario", FormMethod.Post, new { enctype = "multipart/form-data", @id = "Usuario" }))
        {
            <div class="col-md-3">
                <i class="fa-solid fa-car-side"></i>
                @Html.LabelFor(model => model.Automovil)
                @Html.DropDownListFor(model => model.Automovil.IdAutomovil, new SelectList(Model.Automovil.Automoviles, "IdAutomovil", "Placa"), "Selecciona tu placa", new { @class = "form-control" , @id="Placa"})
            </div>
        }
        </div>
            <br><br>
        
            
            <div class="row">
                <div class="col-md-3">
                    
                  
                    @Html.TextBox("horaEntrada", null, new { id = "horaEntrada", placeholder = "Hora de entrada",@class = "form-control" })
                </div>
                <div class="col-md-6">
                    <button class="btn  btn-lg" style="background-color: #8f7b9e;" onclick="mostrarHoraInicial()" ">Entrar</button>
                </div>
            </div>
            <br><br>
            <div class="row">
                <div class="col-md-3">
                    @Html.TextBox("horaSalida", null, new { id = "horaSalida", placeholder = "Hora de salida",@class = "form-control" })
                    
                </div>
                <div class="col-md-6">
                    <button class="btn  btn-lg" style="background-color: #8f7b9e;" onclick="mostrarHoraFinal(); calcularEstancia(); ">Salir </button>
                </div>
            </div>
        <br>
        <br>
        <br>
            <div class="row">
                <div class="col-md-6">
                    <div class="input-group" >
                        <span class="input-group-text" id="resultado"> </span>
                    </div>
                </div>
            </div>
        
           
    </div>
    


<script type="text/javascript">

    var seHaClicado = false;
    function mostrarHoraInicial() 
    {
        if (!seHaClicado) 
        {
            seHaClicado = true;
        var fechaActual = new Date();
        var hora = fechaActual.getHours();
        var minutos = fechaActual.getMinutes();
        var segundos = fechaActual.getSeconds();

        hora = (hora < 10) ? "0" + hora : hora;
        minutos = (minutos < 10) ? "0" + minutos : minutos;
        segundos = (segundos < 10) ? "0" + segundos : segundos;

        var horaExacta = hora + ":" + minutos + ":" + segundos;
        document.getElementById("horaEntrada").value = horaExacta;
         }
         else 
         {
            var placa = document.querySelector("#Placa option:checked").text;
            alert("Ya no puedes hacer clic nuevamente, ya salio la placa " + placa);
         }
    }
    var seHaClicado2 = false;
    function mostrarHoraFinal() {
        if (!seHaClicado2) {
            seHaClicado2 = true;
        var fechaActual = new Date();
        var hora = fechaActual.getHours();
        var minutos = fechaActual.getMinutes();
        var segundos = fechaActual.getSeconds();

        hora = (hora < 10) ? "0" + hora : hora;
        minutos = (minutos < 10) ? "0" + minutos : minutos;
        segundos = (segundos < 10) ? "0" + segundos : segundos;

        var horaExacta = hora + ":" + minutos + ":" + segundos;
        document.getElementById("horaSalida").value = horaExacta;
        }
        else 
         {
            var placa = document.querySelector("#Placa option:checked").text;
            alert("Ya no puedes hacer clic nuevamente, ya salio la placa " + placa);
         }
    }

    function calcularEstancia() {
       
        var placa = document.querySelector("#Placa option:checked").text;
        
        var horaEntrada = document.getElementById("horaEntrada").value;
        var horaSalida = document.getElementById("horaSalida").value;

        var entrada = new Date("2023/06/26 " + horaEntrada);
        var salida = new Date("2023/06/26 " + horaSalida);

        var tiempoEstancia = (salida - entrada) / (1000 * 60 * 60);
        if (tiempoEstancia < 1) 
        {
            costoEstancia = 19;

        }
        else if(tiempoEstancia ==1){
            var costoEstancia = tiempoEstancia * 20;
        }
        else if(tiempoEstancia >1 && tiempoEstancia <= 4 ){
            var costoEstancia = (tiempoEstancia * 4)+20 ;
        }
        else if(tiempoEstancia > 4 ) {
            var costo = ((tiempoEstancia * 4) + 20) * 0.5;
            var costoEstancia = costo + ((tiempoEstancia * 4) + 20);
        }

        document.getElementById("resultado").innerHTML = "ID de Placa: " + placa + "<br>" +
            "Hora de Entrada: " + horaEntrada + "<br>" +
            "Hora de Salida: " + horaSalida + "<br>" +
            "Tiempo de Estancia: " + tiempoEstancia.toFixed(3) + " horas<br>" +
            "Costo de Estancia: $" + costoEstancia.toFixed(2);
    }


</script>

        

PL/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PL.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PL</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="GetAll">Usuarios</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Automovil" asp-action="GetAll">Autos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Estacionamiento" asp-action="Form">Estacionamiento</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - PL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PL/Views/Usuario/Form.cshtml
@model ML.Usuario
@{
    ViewData["Title"] = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <center>
                <h1 style="color:#6EB5FF">Registro de Usuarios</h1>
            </center>
        </div>
        <div class="row">
        </div>
    </div>
    @using (Html.BeginForm("Form", "Usuario", FormMethod.Post, new { enctype = "multipart/form-data", @id = "Usuario" }))
    {
        <div class="row">
            <div class="col-md-3" style="display: none;">
                @Html.TextBoxFor(model => model.IdUsuario, new { @class = "hidden form-control", autocomplete = "off", @id = "IdUsuario" })
            </div>
        </div>
        <div class="row">
            <div class="col-md-3">
                @Html.Label("Nombre")
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1"></span>
                    <div class="input-group mb-3">
                        <span class="input-group-text" id="basic-addon1"><i class="fa-solid fa-user"></i></span>
                        @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control",  @id = "nombre",placeholder="Nombre(s)"})
                    </div>
                </div>
            </div>
                <div class="col-md-3">
                @Html.Label("Apellido")
                    <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1"></span>
                    <div class="input-group mb-3">
                        <span class="input-group-text" id="basic-addon1"><i class="fa-regular fa-user"></i></span>
                        @Html.TextBoxFor(model => model.Apellido, new { @class = "form-control",  @id = "apellido",placeholder="Primer Apellido"})
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                @Html.Label("Usuario")
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1"></span>
                    <div class="input-group mb-3">
                        <span class="input-group-text" id="basic-addon1"><i class="fa-solid fa-face-smile"></i></span>
                        @Html.TextBoxFor(model => model.Username, new { @class = "form-control",  @id = "username",placeholder="Nombre de usuario"})
                    </div>
                </div>
            </div>
                <div class="col-md-3">
                @Html.Label("Contraseña")
                    <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1"></span>
                    <div class="input-group mb-3">
                        <span class="input-group-text" id="basic-addon1"><i class="fa-solid fa-lock"></i></span>
                        @Html.TextBoxFor(model => model.Contrasena, new { @class = "form-control",  @id = "contrasena",placeholder="Contraseña"})
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <i class="fa-solid fa-car-side"></i>
            @Html.LabelFor(model => model.Automovil)
            @Html.DropDownListFor(model => model.Automovil.IdAutomovil, new SelectList(Model.Automovil.Automoviles, "IdAutomovil", "Placa"), "Selecciona tu placa", new { @class = "form-control" })
        </div>
        <br />
        <br />
        <div class="row">
            <div class="col-md-2">
                <input type="submit" value="Guardar" class="btn btn-success" />
            </div>
            <div class="col-md-2">
                @Html.ActionLink("Regresar", "GetAll", "Usuario", htmlAttributes: new { @class = "btn btn-success" })
            </div>
        </div>

    }
</div>

PL/Views/Usuario/GetAll.cshtml
@{
    ViewData["Title"] = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>


<div class="row">
    <div style="float:right;">
        @Html.ActionLink(" Agregar Usuario", "Form", "Usuario", htmlAttributes: new { @class = "btn btn-primary " })
    </div>
</div>
<hr />
<div class="row">
    @if (Model.Usuarios != null)
    {
        <table class="table table-light table-bordered table-responsive table-hover" id="tblUsuario">
            <thead>
                <tr>

                    <td class="table-info text-center" style=" font-weight:bold;">Editar</td>
                    <td class="d-none">IdUsuario</td>
                    <td class="table-info text-center" style=" font-weight:bold;">Nombre</td>
                    <td class="table-info text-center" style=" font-weight:bold;">Username</td>
                    <td class="table-info text-center" style=" font-weight:bold;">Contrasena</td>
                    <td class="d-none">IdAutomovil</td>
                    <td class="table-info text-center" style=" font-weight:bold;">Placas</td>
                    <td class="table-info text-center" style=" font-weight:bold;">Eliminar</td>

                </tr>
            </thead>
            <tbody>

                @foreach (ML.Usuario usuario in Model.Usuarios)
                {
                    <tr>
                        <td class="text-center"><a class="btn btn-warning" href="@Url.Action("Form", "Usuario", new { IdUsuario = usuario.IdUsuario })"><i class="fa-solid fa-eraser"></i> </a></td>
                        <td class="d-none">@usuario.IdUsuario</td>
                        <td class="text-center">@usuario.Nombre @usuario.Apellido</td>
                        <td class="text-center">@usuario.Username </td>
                        <td class="text-center">@usuario.Contrasena</td>
                        <td class="d-none">@usuario.Automovil.IdAutomovil</td>
                        <td class="text-center">@usuario.Automovil.Placa</td>
                        <td style="text-align: center; vertical-align: middle;"><a class="btn btn-danger" href="@Url.Action("Delete", "Usuario", new { IdUsuario= usuario.IdUsuario })" onclick="return confirm('Estas seguro que deseas eliminar este registro?');"><i class="fa-regular fa-circle-xmark"></i></a></td>
                    </tr>
                }
            </tbody>
        </table>

    }
    else
    {
        <div class="alert alert-danger" role="alert">Ocurrio un error al realizar la consulta </div>
    }
</div>

PL/Views/Usuario/Login.cshtml
@model ML.Usuario
@{
    Layout = null;
}


<head>
    <link rel="stylesheet" href="~/css/Logincs.css" />
</head>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

<body>
    <section class="login">
        <div class="login_box">
            <div class="left">
                
                <div class="contact">
                    @using (Html.BeginForm("Login", "Usuario", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                    <form action="">
                        <h3>Login</h3>
                        @Html.TextBoxFor(model => model.Username, new { @class = "form-control form-control-lg", @id = "txtUserName", @placeholder= "Username" })
                        <br />
                        <br />

                        @Html.TextBoxFor(model => model.Contrasena, new { @class = "form-control form-control-lg", @id = "txtContrasena", @placeholder= "Contraseña" })
                        @*<input type="text" placeholder="USERNAME">
                        <input type="text" placeholder="PASSWORD">*@
                        <button class="submit">Entrar</button>
                    </form>
                    }
                </div>
               
            </div>
            <div class="right">
                <div class="right-text">
                    <h2>KARIIINA</h2>
                    <h5>ESTACIONAMIENTO</h5>
                </div>
            </div>
        </div>
    </section>
</body>

</html>

PL/Views/Usuario/LoginModal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="ModalLogin">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close" name="eliminar">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Message</h5>
            </div>
            <div class="modal-footer">
                @Html.ActionLink("Regresar", "Login", "Usuario", htmlAttributes: new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
</div>

<script>
    $('#ModalLogin').modal();
</script>